services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: skydan
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - db
    restart: unless-stopped
  skydan-api:
    container_name: skydan-api
    image: skydan111/skydan-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/customer
    ports:
      - "8088:8080"
    networks:
      - db
    depends_on:
      - db
    restart: unless-stopped
  skydan-react:
    container_name: skydan-react
    image: skydan111/skydan-react
    build:
      context: frontend/react
      args:
        api_base_url: http://localhost:8088
    ports:
      - "3000:5173"
    depends_on:
      - skydan-api
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  postgres:
  pgadmin: